-- Flyway-managed schema: mirrors the JPA entities, replacing ddl-auto: update/create-drop.
-- This migration runs for the default (PostgreSQL) profile. The demo profile disables
-- Flyway and keeps using Hibernate create-drop against in-memory H2.

CREATE TABLE institutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    contact_name VARCHAR(120),
    contact_email VARCHAR(120) NOT NULL UNIQUE,
    phone VARCHAR(30),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    role VARCHAR(20) NOT NULL,
    institution_id BIGINT,
    license_code_id BIGINT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE license_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    institution_id BIGINT NOT NULL,
    total_seats INT NOT NULL,
    used_seats INT NOT NULL,
    valid_from DATE NOT NULL,
    valid_until DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_license_institution FOREIGN KEY (institution_id) REFERENCES institutions(id)
);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(500),
    level VARCHAR(10) NOT NULL,
    archived BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    exam_year INT NOT NULL,
    section VARCHAR(15) NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(500) NOT NULL,
    option_b VARCHAR(500) NOT NULL,
    option_c VARCHAR(500) NOT NULL,
    option_d VARCHAR(500) NOT NULL,
    correct_option VARCHAR(5) NOT NULL,
    explanation TEXT,
    marks INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_question_course FOREIGN KEY (course_id) REFERENCES courses(id)
);

CREATE INDEX idx_question_course_year ON questions(course_id, exam_year);

CREATE TABLE quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    exam_year INT NOT NULL,
    timed BOOLEAN NOT NULL,
    time_limit_seconds INT,
    status VARCHAR(15) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    submitted_at TIMESTAMP,
    total_questions INT NOT NULL,
    answered_count INT NOT NULL,
    correct_count INT NOT NULL,
    score_percent DOUBLE PRECISION NOT NULL,
    duration_seconds BIGINT NOT NULL,
    last_active_at TIMESTAMP,
    CONSTRAINT fk_attempt_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_attempt_course FOREIGN KEY (course_id) REFERENCES courses(id)
);

CREATE INDEX idx_attempt_user ON quiz_attempts(user_id);

CREATE TABLE attempt_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option VARCHAR(5),
    correct BOOLEAN NOT NULL,
    answered_at TIMESTAMP NOT NULL,
    time_spent_seconds INT NOT NULL,
    UNIQUE (attempt_id, question_id),
    CONSTRAINT fk_answer_attempt FOREIGN KEY (attempt_id) REFERENCES quiz_attempts(id),
    CONSTRAINT fk_answer_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    plan VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    payment_ref VARCHAR(60),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_subscription_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE motivational_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    author VARCHAR(100) NOT NULL
);
